let token=localStorage.getItem('nexora_token');
let state={projects:[],policies:[],ops:[],files:[],currentProject:null,currentFile:null};
const $=s=>document.querySelector(s);
async function api(url,opt={}){opt.headers={'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(opt.headers||{})};const r=await fetch(url,opt);const j=await r.json();if(!j.success)throw new Error(j.error?.message||'Request failed');return j.data}
function login(){document.querySelector('#app').innerHTML='<div class="auth"><div class="auth-card"><div class="logo">NEXORA<span> AI</span></div><div class="eyebrow">PERSONAL AI DEVELOPMENT FACTORY</div><h1>Build software with an engineering agent.</h1><p>Real projects, files, terminal, tests, builds and deployment controls.</p><input id="u" value="admin" placeholder="Username"><input id="p" type="password" placeholder="Password"><button id="go">Enter workspace</button><small id="e"></small></div></div>';$('#go').onclick=async()=>{try{const x=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:$('#u').value,password:$('#p').value})});token=x.token;localStorage.setItem('nexora_token',token);render()}catch(e){$('#e').textContent=e.message}}}
async function render(){try{const [me,health,projects,policies,ops]=await Promise.all([api('/api/me'),api('/api/health'),api('/api/projects'),api('/api/policies'),api('/api/operations')]);state={...state,projects,policies,ops,_health:health,currentProject:state.currentProject||projects[0]};if(state.currentProject)await loadFiles();document.querySelector('#app').innerHTML=layout(me,health);bind()}catch(e){if(/Authentication|Session/.test(e.message)){localStorage.removeItem('nexora_token');token=null;login()}else document.querySelector('#app').innerHTML='<div class="error-screen">'+e.message+'</div>'}}
async function loadFiles(){if(!state.currentProject)return;try{state.files=await api('/api/projects/'+state.currentProject.id+'/files')}catch{}}
function layout(me,health){const p=state.currentProject;return '<div class="app"><aside class="sidebar"><div class="brand">NEXORA <i>AI</i></div><div class="factory">DEVELOPMENT FACTORY</div><nav>'+['workspace|⌁ AI Workspace','files|▤ Files','terminal|>_ Terminal','builds|◈ Builds & Tests','git|⑂ Git','deploy|↗ Deployments','settings|⚙ Settings','admin|◉ Master Admin'].map(x=>{const [id,label]=x.split('|');return '<button class="nav" data-view="'+id+'">'+label+'</button>'}).join('')+'</nav><div class="side-bottom"><span class="online"></span> API online<div>'+me.username+' · '+me.role+'</div><button id="logout" class="logout">Log out</button></div></aside><main class="main"><header><div><div class="crumb">NEXORA AI / '+(p?p.name:'No project')+'</div><h1 id="title">AI Workspace</h1></div><div class="project-select"><select id="project">'+state.projects.map(x=>'<option value="'+x.id+'" '+(p&&x.id===p.id?'selected':'')+'>'+x.name+'</option>').join('')+'</select><button id="newp">+ Project</button></div></header><section id="view"></section></main></div>'}
function show(view){const v=$('#view');$('#title').textContent={workspace:'AI Workspace',files:'Files & Code',terminal:'Terminal',builds:'Builds & Tests',git:'Git',deploy:'Deployments',settings:'Settings',admin:'Master Admin'}[view]||'AI Workspace';if(view==='workspace')v.innerHTML=workspace();if(view==='files')v.innerHTML=files();if(view==='terminal')v.innerHTML=terminal();if(view==='builds')v.innerHTML=builds();if(view==='git')v.innerHTML=git();if(view==='deploy')v.innerHTML=deploy();if(view==='settings')v.innerHTML=settings();if(view==='admin')v.innerHTML=admin();bindView(view)}
function workspace(){return '<div class="hero"><div><div class="eyebrow">AUTONOMOUS ENGINEERING WORKSPACE</div><h2>What are we building?</h2><p>Give Nexora a requirement. It analyzes project context and returns an executable engineering plan. Execution remains subject to Master Admin policies.</p></div><div class="orb">N</div></div><div class="workspace-grid"><div class="panel chat"><div class="panel-head"><span>AI ENGINEER</span><b>Context-aware</b></div><div id="chatlog" class="chatlog"><div class="msg ai">Tell me what you want to build or change in this project.</div></div><div class="composer"><textarea id="req" placeholder="Example: Build a premium ecommerce website with auth, products, cart, orders and admin..."></textarea><button id="plan">Analyze & Plan ↗</button></div></div><div class="panel"><div class="panel-head"><span>LIVE SYSTEM</span></div><div class="metrics"><div><small>PROJECTS</small><strong>'+state.projects.length+'</strong></div><div><small>MODEL</small><strong>'+((state._health?.model?.available)?'ONLINE':'OFFLINE')+'</strong></div><div><small>OPERATIONS</small><strong>'+state.ops.length+'</strong></div></div><div class="pipeline"><span>Requirement</span><span>Context</span><span>Plan</span><span>Execute</span><span>Test</span><span>Verify</span></div></div></div>'}
function files(){return '<div class="editor-layout"><div class="panel filetree"><div class="panel-head"><span>PROJECT FILES</span><button id="index">Index</button></div><div id="filelist">'+state.files.map(f=>'<button class="file" data-file="'+encodeURIComponent(f.path)+'"><span>'+icon(f.language)+'</span>'+f.path+'</button>').join('')+'</div></div><div class="panel editor"><div class="panel-head"><span id="filename">'+(state.currentFile||'Select a file')+'</span><button id="save">Save</button></div><textarea id="code" spellcheck="false" placeholder="Select a project file to edit."></textarea></div></div>'}
function icon(l){return ({javascript:'JS',typescript:'TS',python:'PY',html:'HT',css:'CS',json:'{}',kotlin:'KT'})[l]||'·'}
function terminal(){return '<div class="panel terminal-panel"><div class="panel-head"><span>REAL PROJECT TERMINAL</span><span class="pill">POLICY CONTROLLED</span></div><textarea id="cmd" class="cmd" placeholder="npm test&#10;npm run build"></textarea><button id="run">Run command</button><pre id="termout">Output will appear here.</pre></div>'}
function builds(){return '<div class="two"><div class="panel action-card"><div class="eyebrow">BUILD ENGINE</div><h2>Build the selected project</h2><p>Runs the real build command inside the project workspace.</p><input id="buildcmd" value="npm run build"><button id="build">Run build</button></div><div class="panel action-card"><div class="eyebrow">TEST ENGINE</div><h2>Verify it</h2><p>Runs the real test suite and reports the actual result.</p><input id="testcmd" value="npm test"><button id="test">Run tests</button></div></div><pre id="buildout" class="output"></pre>'}
function git(){return '<div class="panel"><div class="panel-head"><span>GIT WORKSPACE</span><button id="gitrefresh">Refresh status</button></div><pre id="gitout">Loading...</pre></div>'}
function deploy(){return '<div class="panel action-card"><div class="eyebrow">DEPLOYMENT ENGINE</div><h2>Verified deployment</h2><p>Nexora will only report deployment after an authorized provider is configured and the real deployment/health check succeeds.</p><button id="deploy">Start deployment</button><pre id="deployout"></pre></div>'}
function settings(){return '<div class="panel"><div class="eyebrow">PLATFORM</div><h2>Project & model configuration</h2><p>Model server status and runtime configuration are controlled by the server environment.</p><div class="info-row"><span>Model endpoint</span><b>'+((state._health?.model?.config?.baseUrl)||'Not configured')+'</b></div><div class="info-row"><span>Current project</span><b>'+((state.currentProject&&state.currentProject.root)||'None')+'</b></div></div>'}
function admin(){return '<div class="panel"><div class="eyebrow">OUTSIDE AI CONTROL</div><h2>Master Admin Policy Engine</h2><p>These controls are enforced by the backend. The AI cannot change its own permissions.</p>'+state.policies.map(p=>'<label class="policy"><span>'+p.key+'</span><input type="checkbox" data-key="'+p.key+'" '+(p.enabled?'checked':'')+'></label>').join('')+'</div>'}
function bind(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#logout').onclick=()=>{localStorage.removeItem('nexora_token');token=null;login()};$('#newp').onclick=async()=>{const name=prompt('Project name');if(!name)return;const root='./workspace/'+name.toLowerCase().replace(/[^a-z0-9]+/g,'-');await api('/api/projects',{method:'POST',body:JSON.stringify({name,root})});render()};$('#project').onchange=()=>{state.currentProject=state.projects.find(x=>x.id===$('#project').value);show('workspace')};show('workspace')}
async function bindView(view){if(view==='workspace'){$('#plan').onclick=async()=>{const req=$('#req').value.trim();if(!req)return;$('#chatlog').innerHTML+='<div class="msg user">'+escapeHtml(req)+'</div><div class="msg ai">Analyzing project context and requesting the connected coding model…</div>';try{const x=await api('/api/projects/'+state.currentProject.id+'/plan',{method:'POST',body:JSON.stringify({request:req})});$('#chatlog').lastElementChild.textContent=JSON.stringify(x.answer||x,null,2)}catch(e){$('#chatlog').lastElementChild.textContent='BLOCKED / ERROR: '+e.message}}}
if(view==='files'){document.querySelectorAll('.file').forEach(b=>b.onclick=async()=>{const f=decodeURIComponent(b.dataset.file);const x=await api('/api/projects/'+state.currentProject.id+'/file?path='+encodeURIComponent(f));state.currentFile=f;$('#filename').textContent=f;$('#code').value=x.content});$('#save').onclick=async()=>{await api('/api/projects/'+state.currentProject.id+'/file',{method:'PUT',body:JSON.stringify({path:state.currentFile,content:$('#code').value})});alert('Saved to project filesystem');};$('#index').onclick=async()=>{await api('/api/projects/'+state.currentProject.id+'/index',{method:'POST'});await loadFiles();show('files')}}
if(view==='terminal')$('#run').onclick=async()=>{try{const x=await api('/api/projects/'+state.currentProject.id+'/terminal',{method:'POST',body:JSON.stringify({command:$('#cmd').value})});$('#termout').textContent=(x.stdout||'')+(x.stderr?'\\n'+x.stderr:'')}catch(e){$('#termout').textContent='ERROR: '+e.message}}
if(view==='builds'){const run=async(type)=>{try{const x=await api('/api/projects/'+state.currentProject.id+'/'+type,{method:'POST',body:JSON.stringify({command:$('#'+type+'cmd').value})});$('#buildout').textContent=JSON.stringify(x,null,2)}catch(e){$('#buildout').textContent='FAILED: '+e.message}};$('#build').onclick=()=>run('build');$('#test').onclick=()=>run('test')}
if(view==='git'){const load=async()=>{try{const x=await api('/api/projects/'+state.currentProject.id+'/git');$('#gitout').textContent=x.stdout||x.stderr||JSON.stringify(x,null,2)}catch(e){$('#gitout').textContent=e.message}};$('#gitrefresh').onclick=load;load()}
if(view==='deploy')$('#deploy').onclick=async()=>{try{$('#deployout').textContent=JSON.stringify(await api('/api/projects/'+state.currentProject.id+'/deploy',{method:'POST'}),null,2)}catch(e){$('#deployout').textContent='NOT DEPLOYED: '+e.message}}
if(view==='admin')document.querySelectorAll('[data-key]').forEach(x=>x.onchange=async()=>{try{await api('/api/policies/'+x.dataset.key,{method:'PATCH',body:JSON.stringify({enabled:x.checked})})}catch(e){x.checked=!x.checked;alert(e.message)}})}
function escapeHtml(s){return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
if(token)render();else login();