let token=localStorage.getItem('nexora_token');let state={projects:[],currentProject:null};
const $=s=>document.querySelector(s);
async function api(url,opt={}){opt.headers={'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(opt.headers||{})};const r=await fetch(url,opt);const j=await r.json();if(!j.success)throw new Error(j.error?.message||'Request failed');return j.data}
function login(){document.querySelector('#app').innerHTML='<main class="auth"><section class="auth-card"><div class="logo">NEXORA<span> AI</span></div><div class="muted">PERSONAL CODING ENGINEERING AI</div><h1>Build with Nexora.</h1><p>Describe a website, Android app, bug fix, or engineering task. Nexora works inside the selected project workspace.</p><input id="u" value="admin" placeholder="Username"><input id="p" type="password" placeholder="Password"><button id="go">Continue</button><small id="e"></small></section></main>';$('#go').onclick=async()=>{try{const x=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:$('#u').value,password:$('#p').value})});token=x.token;localStorage.setItem('nexora_token',token);render()}catch(e){$('#e').textContent=e.message}}}
async function render(){try{const [me,projects]=await Promise.all([api('/api/me'),api('/api/projects')]);state.projects=projects;state.currentProject=state.currentProject||projects[0];document.querySelector('#app').innerHTML=layout(me);bind();}catch(e){if(/Authentication|Session/.test(e.message)){localStorage.removeItem('nexora_token');token=null;login()}else document.querySelector('#app').innerHTML='<main class="center">'+e.message+'</main>'}}
function layout(me){return '<div class="shell"><aside class="left"><div class="brand">NEXORA <span>AI</span></div><button class="newchat" id="newchat">＋ New project</button><div class="section-title">PROJECTS</div><div id="projects">'+state.projects.map(p=>'<button class="project '+(state.currentProject?.id===p.id?'active':'')+'" data-id="'+p.id+'"><span>◈</span>'+escapeHtml(p.name)+'</button>').join('')+'</div><div class="left-bottom"><a href="/admin.html">Master Admin ↗</a><button id="logout">Log out</button></div></aside><main class="chat-main"><header class="topbar"><div class="mobile-brand">NEXORA AI</div><div class="model-badge">● Local engineering runtime</div><select id="projectSelect">'+state.projects.map(p=>'<option value="'+p.id+'" '+(state.currentProject?.id===p.id?'selected':'')+'>'+escapeHtml(p.name)+'</option>').join('')+'</select></header><section class="conversation"><div class="welcome"><div class="mark">N</div><h1>What are we building?</h1><p>Ask Nexora to create, inspect, debug, test, or improve your project.</p><div class="cards"><button data-prompt="Build a production-ready responsive website with authentication, database, admin panel and deployment configuration.">Build a website</button><button data-prompt="Build an Android app with a real project structure, build configuration and tests.">Build Android app</button><button data-prompt="Inspect this project for bugs, security issues and build failures, then fix them.">Debug & repair</button></div></div><div id="messages"></div></section><div class="composer-wrap"><div class="composer"><textarea id="req" rows="1" placeholder="Message Nexora AI…"></textarea><button id="send" aria-label="Send">↑</button></div><div class="hint">Nexora can edit files, run permitted commands, build and test. No operation is reported successful unless the backend returns success.</div></div></main></div>'}
function add(role,text){const m=$('#messages');m.insertAdjacentHTML('beforeend','<div class="bubble '+role+'"><div class="bubble-label">'+(role==='user'?'You':'Nexora AI')+'</div><pre>'+escapeHtml(text)+'</pre></div>');m.lastElementChild.scrollIntoView({behavior:'smooth',block:'end'})}
async function send(){const req=$('#req').value.trim();if(!req||!state.currentProject)return;$('#req').value='';add('user',req);add('ai','Working through the project…');const pending=$('#messages').lastElementChild.querySelector('pre');try{const x=await api('/api/projects/'+state.currentProject.id+'/execute',{method:'POST',body:JSON.stringify({request:req})});pending.textContent=x.message||JSON.stringify(x,null,2)}catch(e){pending.textContent='ERROR: '+e.message}}
function bind(){$('#send').onclick=send;$('#req').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('#req').value=b.dataset.prompt;send()});$('#logout').onclick=()=>{localStorage.removeItem('nexora_token');token=null;login()};document.querySelectorAll('.project').forEach(b=>b.onclick=()=>{state.currentProject=state.projects.find(p=>p.id===b.dataset.id);render()});$('#projectSelect').onchange=()=>{state.currentProject=state.projects.find(p=>p.id===$('#projectSelect').value);render()};$('#newchat').onclick=async()=>{const name=prompt('Project name');if(!name)return;const root='./workspace/'+name.toLowerCase().replace(/[^a-z0-9]+/g,'-');await api('/api/projects',{method:'POST',body:JSON.stringify({name,root})});render()}}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
if(token)render();else login();
