import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {migrate,db} from '../database/db.js';import {ensureAdmin,login,auth} from './auth.js';import {allPolicies,setPolicy} from '../admin/policy.js';import {id,now} from '../shared/security.js';import {err} from '../shared/errors.js';import {indexProject} from '../repository-indexer/index.js';import {getMemory,setMemory} from '../project-memory/index.js';import {health as modelHealth} from '../model-server/adapter.js';import {plan} from '../orchestrator/index.js';import {execCommand} from '../tools/terminal.js';import {build} from '../build-engine/index.js';import {test as runTests} from '../test-engine/index.js';import {deploy} from '../deployment-engine/index.js';import {requirePolicy} from '../admin/policy.js';
migrate();ensureAdmin();
const root=path.dirname(fileURLToPath(import.meta.url));const frontend=path.resolve(root,'../frontend');
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
async function body(req){let s='';for await(const c of req)s+=c;return s?JSON.parse(s):{};}
function project(id){const p=db.prepare('SELECT * FROM projects WHERE id=?').get(id);if(!p)throw err('PROJECT_NOT_FOUND','Project not found',404);return p;}
async function route(req,res){const u=new URL(req.url,'http://localhost');try{
if(req.method==='GET'&&u.pathname==='/api/health'){return json(res,200,{success:true,data:{app:'Nexora AI',time:now(),node:process.version,model:await modelHealth(),policies:allPolicies()}})}
if(req.method==='POST'&&u.pathname==='/api/auth/login'){const b=await body(req);return json(res,200,{success:true,data:login(b.username,b.password)})}
const user=auth(req);
if(req.method==='GET'&&u.pathname==='/api/me')return json(res,200,{success:true,data:user});
if(req.method==='GET'&&u.pathname==='/api/policies')return json(res,200,{success:true,data:allPolicies()});
if(req.method==='PATCH'&&u.pathname.startsWith('/api/policies/')){if(user.role!=='admin')throw err('FORBIDDEN','Admin required',403);const key=u.pathname.split('/').pop(),b=await body(req);setPolicy(key,!!b.enabled);db.prepare('INSERT INTO audit(user_id,action,details,created_at) VALUES(?,?,?,?)').run(user.id,'policy.update',JSON.stringify({key,enabled:!!b.enabled}),now());return json(res,200,{success:true,data:allPolicies()});}
if(req.method==='GET'&&u.pathname==='/api/projects')return json(res,200,{success:true,data:db.prepare('SELECT * FROM projects ORDER BY updated_at DESC').all()});
if(req.method==='POST'&&u.pathname==='/api/projects'){const b=await body(req);if(!b.name||!b.root)throw err('VALIDATION','name and root are required');const p={id:id(),name:b.name,root:path.resolve(b.root),created_at:now(),updated_at:now()};fs.mkdirSync(p.root,{recursive:true});db.prepare('INSERT INTO projects VALUES(?,?,?,?,?)').run(p.id,p.name,p.root,p.created_at,p.updated_at);setMemory(p.id,'architecture','stack',{root:p.root});return json(res,201,{success:true,data:p});}
const pm=u.pathname.match(/^\/api\/projects\/([^/]+)(.*)$/);if(pm){const p=project(pm[1]),sub=pm[2];if(req.method==='POST'&&sub==='/index'){return json(res,200,{success:true,data:indexProject(p)})}if(req.method==='GET'&&sub==='/memory')return json(res,200,{success:true,data:getMemory(p.id)});if(req.method==='POST'&&sub==='/memory'){const b=await body(req);setMemory(p.id,b.type||'decision',b.key||id(),b.value);return json(res,201,{success:true,data:getMemory(p.id)})}if(req.method==='POST'&&sub==='/terminal'){const b=await body(req);return json(res,200,{success:true,data:await execCommand(p,b.command)})}
if(req.method==='GET'&&sub==='/files'){const rows=db.prepare('SELECT path,language,size,updated_at FROM repo_files WHERE project_id=? ORDER BY path').all(p.id);return json(res,200,{success:true,data:rows})}
if(req.method==='GET'&&sub==='/file'){const rel=u.searchParams.get('path');if(!rel)throw err('VALIDATION','path is required');const target=path.resolve(p.root,rel);if(!target.startsWith(p.root+path.sep))throw err('PATH_DENIED','Path outside project',403);if(!fs.existsSync(target)||!fs.statSync(target).isFile())throw err('FILE_NOT_FOUND','File not found',404);return json(res,200,{success:true,data:{path:rel,content:fs.readFileSync(target,'utf8')}})}
if(req.method==='PUT'&&sub==='/file'){requirePolicy('file_write');const b=await body(req);if(!b.path||typeof b.content!=='string')throw err('VALIDATION','path and content are required');const target=path.resolve(p.root,b.path);if(!target.startsWith(p.root+path.sep))throw err('PATH_DENIED','Path outside project',403);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,b.content,'utf8');return json(res,200,{success:true,data:{path:b.path,saved:true}})}
if(req.method==='POST'&&sub==='/build'){const b=await body(req);return json(res,200,{success:true,data:await build(p,b.command||'npm run build')})}
if(req.method==='POST'&&sub==='/test'){const b=await body(req);return json(res,200,{success:true,data:await runTests(p,b.command||'npm test')})}
if(req.method==='GET'&&sub==='/git'){const r=await execCommand(p,'git status --short && printf "\\n---BRANCH---\\n" && git branch --show-current');return json(res,200,{success:true,data:r})}
if(req.method==='POST'&&sub==='/deploy'){return json(res,200,{success:true,data:await deploy(p)})}
if(req.method==='POST'&&sub==='/plan'){const b=await body(req);return json(res,200,{success:true,data:await plan({project:p,request:b.request})})}}
if(req.method==='GET'&&u.pathname==='/api/operations')return json(res,200,{success:true,data:db.prepare('SELECT * FROM operations ORDER BY id DESC LIMIT 100').all()});
if(req.method==='GET'&&u.pathname==='/api/credentials')return json(res,200,{success:true,data:db.prepare('SELECT id,name,created_at FROM credentials').all()});
throw err('NOT_FOUND','Route not found',404);
}catch(e){console.error('[REAL ERROR]',e);return json(res,e.status||500,{success:false,error:{code:e.code||'INTERNAL_ERROR',message:e.message,details:e.details||{}}});}}
const server=http.createServer(async(req,res)=>{if(req.url.startsWith('/api/'))return route(req,res);let p=req.url==='/'?'/index.html':req.url;const file=path.normalize(path.join(frontend,p));if(!file.startsWith(frontend)||!fs.existsSync(file)||!fs.statSync(file).isFile())return json(res,404,{success:false,error:{code:'NOT_FOUND',message:'Not found'}});const ext=path.extname(file);const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(file).pipe(res);});
const port=Number(process.env.PORT||process.env.NEXORA_PORT||8787),host=process.env.NEXORA_HOST||'0.0.0.0';server.listen(port,host,()=>console.log(`Nexora AI running at http://${host}:${port}`));
