import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {migrate,db} from '../database/db.js';import {ensureAdmin,login,auth} from './auth.js';import {allPolicies,setPolicy} from '../admin/policy.js';import {id,now} from '../shared/security.js';import {err} from '../shared/errors.js';import {indexProject} from '../repository-indexer/index.js';import {getMemory,setMemory} from '../project-memory/index.js';import {health as modelHealth} from '../model-server/adapter.js';import {plan} from '../orchestrator/index.js';import {execCommand} from '../tools/terminal.js';import {build} from '../build-engine/index.js';import {test as runTests} from '../test-engine/index.js';import {deploy} from '../deployment-engine/index.js';import {requirePolicy} from '../admin/policy.js';import {execute as executeAgent} from '../agent-engine/index.js';import {createZip} from '../export-engine/index.js';import {put as putCredential,list as listCredentials} from '../credential-vault/index.js';
import {normalizeProjectSpec,buildBrief} from '../project-spec/index.js';
import {buildAndroid} from '../android-engine/index.js';
import {scanSecurity} from '../security-engine/index.js';

migrate();ensureAdmin();
const root=path.dirname(fileURLToPath(import.meta.url));const frontend=path.resolve(root,'../frontend');
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>12*1024*1024)throw err('PAYLOAD_TOO_LARGE','Request body is too large',413)}return s?JSON.parse(s):{};}
function safeProjectName(name){return String(name||'My Project').trim().replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)||'my-project';}
function projectSpecFromRow(p){return {type:p.type||'website',frontend:p.frontend||'auto',backend:p.backend||'auto',database:p.database_kind||'auto',designReference:p.reference_path||'',requirements:getMemory(p.id).find(x=>x.type==='spec'&&x.key==='requirements')?.value||''};}
function project(id){const p=db.prepare('SELECT * FROM projects WHERE id=?').get(id);if(!p)throw err('PROJECT_NOT_FOUND','Project not found',404);return p;}
function adminUser(req){return auth(req);}
async function route(req,res){const u=new URL(req.url,'http://localhost');try{
if(req.method==='GET'&&u.pathname==='/api/health'){
  let dbOk=false;try{db.prepare('SELECT 1').get();dbOk=true;}catch{}
  return json(res,dbOk?200:503,{success:dbOk,data:{app:'Nexora AI',time:now(),node:process.version,database:dbOk?'ok':'error',policies:allPolicies()}});
}
if(req.method==='GET'&&u.pathname==='/api/health/model')return json(res,200,{success:true,data:await modelHealth()});
if(req.method==='POST'&&u.pathname==='/api/auth/login'){const b=await body(req);return json(res,200,{success:true,data:login(b.username,b.password)});}
if(req.method==='GET'&&u.pathname==='/api/me')return json(res,200,{success:true,data:adminUser(req)});
if(req.method==='GET'&&u.pathname==='/api/project-types')return json(res,200,{success:true,data:{types:['website','android','cyber'],frontends:['auto','HTML/CSS/JS','React','Next.js','Vue'],backends:['auto','none','Node.js/Express','Node.js/Fastify','Python/FastAPI'],databases:['auto','none','SQLite','PostgreSQL','Turso']}});

if(req.method==='GET'&&u.pathname==='/api/policies'){adminUser(req);return json(res,200,{success:true,data:allPolicies()});}
if(req.method==='GET'&&u.pathname==='/api/integrations'){const user=adminUser(req);if(user.role!=='admin')throw err('FORBIDDEN','Admin required',403);const names=['github_token','render_deploy_hook_url','vercel_deploy_hook_url','cloudflare_deploy_hook_url','hostinger_deploy_hook_url'];const stored=new Set(listCredentials().map(x=>x.name));return json(res,200,{success:true,data:names.map(name=>({name,configured:stored.has(name)}))});}
if(req.method==='PUT'&&u.pathname.startsWith('/api/integrations/')){const user=adminUser(req);if(user.role!=='admin')throw err('FORBIDDEN','Admin required',403);const name=u.pathname.split('/').pop();const allowed=new Set(['github_token','render_deploy_hook_url','vercel_deploy_hook_url','cloudflare_deploy_hook_url','hostinger_deploy_hook_url']);if(!allowed.has(name))throw err('INTEGRATION_UNKNOWN','Unknown integration credential',404);const b=await body(req);if(typeof b.value!=='string'||!b.value.trim())throw err('VALIDATION','value is required');putCredential(name,b.value.trim());db.prepare('INSERT INTO audit(user_id,action,details,created_at) VALUES(?,?,?,?)').run(user.id,'integration.update',JSON.stringify({name}),now());return json(res,200,{success:true,data:{name,configured:true}});}
if(req.method==='PATCH'&&u.pathname.startsWith('/api/policies/')){const user=adminUser(req);if(user.role!=='admin')throw err('FORBIDDEN','Admin required',403);const key=u.pathname.split('/').pop(),b=await body(req);setPolicy(key,!!b.enabled);db.prepare('INSERT INTO audit(user_id,action,details,created_at) VALUES(?,?,?,?)').run(user.id,'policy.update',JSON.stringify({key,enabled:!!b.enabled}),now());return json(res,200,{success:true,data:allPolicies()});}

if(req.method==='GET'&&u.pathname==='/api/projects')return json(res,200,{success:true,data:db.prepare('SELECT * FROM projects ORDER BY updated_at DESC').all()});
if(req.method==='POST'&&u.pathname==='/api/projects'){const b=await body(req);if(!b.name)throw err('VALIDATION','name is required');const spec=normalizeProjectSpec(b);const safe=safeProjectName(b.name);const p={id:id(),name:String(b.name).trim(),root:path.resolve(b.root||('./workspace/'+safe+'-'+id().slice(0,8))),type:spec.type,frontend:spec.frontend,backend:spec.backend,database_kind:spec.database,reference_path:null,created_at:now(),updated_at:now()};fs.mkdirSync(p.root,{recursive:true});db.prepare('INSERT INTO projects(id,name,root,created_at,updated_at,type,frontend,backend,database_kind,reference_path) VALUES(?,?,?,?,?,?,?,?,?,?)').run(p.id,p.name,p.root,p.created_at,p.updated_at,p.type,p.frontend,p.backend,p.database_kind,p.reference_path);setMemory(p.id,'architecture','stack',JSON.stringify({root:p.root,type:p.type,frontend:p.frontend,backend:p.backend,database:p.database}));if(spec.requirements)setMemory(p.id,'spec','requirements',spec.requirements);return json(res,201,{success:true,data:p,spec});}
const pm=u.pathname.match(/^\/api\/projects\/([^/]+)(.*)$/);if(pm){const p=project(pm[1]),sub=pm[2];
if(req.method==='POST'&&sub==='/index')return json(res,200,{success:true,data:indexProject(p)});
if(req.method==='GET'&&sub==='/memory')return json(res,200,{success:true,data:getMemory(p.id)});
if(req.method==='POST'&&sub==='/memory'){const b=await body(req);setMemory(p.id,b.type||'decision',b.key||id(),b.value);return json(res,201,{success:true,data:getMemory(p.id)})}
if(req.method==='POST'&&sub==='/reference'){const b=await body(req);if(typeof b.dataUrl!=='string'||!/^data:image\/(png|jpeg|jpg|webp);base64,/i.test(b.dataUrl))throw err('VALIDATION','reference image must be a PNG, JPEG or WebP data URL');if(b.dataUrl.length>9*1024*1024)throw err('PAYLOAD_TOO_LARGE','Reference image is too large; maximum is about 6MB',413);const m=b.dataUrl.match(/^data:image\/(png|jpeg|jpg|webp);base64,(.+)$/i);const ext=(m[1].toLowerCase()==='jpeg'||m[1].toLowerCase()==='jpg')?'jpg':m[1].toLowerCase();const rel='.nexora/reference.'+ext;const target=path.resolve(p.root,rel);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,Buffer.from(m[2],'base64'));db.prepare('UPDATE projects SET reference_path=?,updated_at=? WHERE id=?').run(rel,now(),p.id);setMemory(p.id,'spec','design_reference',rel);return json(res,201,{success:true,data:{path:rel,size:fs.statSync(target).size}})}
if(req.method==='POST'&&sub==='/terminal'){requirePolicy('terminal');const b=await body(req);return json(res,200,{success:true,data:await execCommand(p,b.command)})}
if(req.method==='GET'&&sub==='/export.zip'){requirePolicy('export_zip');const z=await createZip(p);res.writeHead(200,{'Content-Type':'application/zip','Content-Length':String(z.bytes),'Content-Disposition':'attachment; filename="'+z.filename+'"','Cache-Control':'no-store'});const stream=fs.createReadStream(z.file);stream.on('close',()=>{try{fs.rmSync(path.dirname(z.file),{recursive:true,force:true})}catch{}});return stream.pipe(res)}
if(req.method==='POST'&&sub==='/github'){requirePolicy('github_push');const b=await body(req);const result=await deploy(p,{provider:'github',repo:b.repo,branch:b.branch||'main',message:b.message});return json(res,200,{success:true,data:result})}
if(req.method==='GET'&&sub==='/files')return json(res,200,{success:true,data:db.prepare('SELECT path,language,size,updated_at FROM repo_files WHERE project_id=? ORDER BY path').all(p.id)});
if(req.method==='GET'&&sub==='/file'){const rel=u.searchParams.get('path');if(!rel)throw err('VALIDATION','path is required');const target=path.resolve(p.root,rel);if(!target.startsWith(p.root+path.sep))throw err('PATH_DENIED','Path outside project',403);if(!fs.existsSync(target)||!fs.statSync(target).isFile())throw err('FILE_NOT_FOUND','File not found',404);return json(res,200,{success:true,data:{path:rel,content:fs.readFileSync(target,'utf8')}})}
if(req.method==='PUT'&&sub==='/file'){requirePolicy('file_write');const b=await body(req);if(!b.path||typeof b.content!=='string')throw err('VALIDATION','path and content are required');const target=path.resolve(p.root,b.path);if(!target.startsWith(p.root+path.sep))throw err('PATH_DENIED','Path outside project',403);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,b.content,'utf8');return json(res,200,{success:true,data:{path:b.path,saved:true}})}
if(req.method==='POST'&&sub==='/build'){requirePolicy('deployment');const b=await body(req);const result=await build(p,b.command||'npm run build');return json(res,result.code===0?200:422,{success:result.code===0,data:result,error:result.code===0?undefined:{code:'BUILD_FAILED',message:'Build command failed',details:result}})}
if(req.method==='POST'&&sub==='/android-build'){const b=await body(req);return json(res,200,{success:true,data:await buildAndroid(p,{variant:b.variant||'debug'})})}
if(req.method==='GET'&&sub==='/apk'){const rel=u.searchParams.get('path');if(!rel)throw err('VALIDATION','path is required');const target=path.resolve(p.root,rel);if(!target.startsWith(p.root+path.sep)||!target.toLowerCase().endsWith('.apk'))throw err('PATH_DENIED','Invalid APK path',403);if(!fs.existsSync(target)||!fs.statSync(target).isFile())throw err('FILE_NOT_FOUND','APK not found',404);res.writeHead(200,{'Content-Type':'application/vnd.android.package-archive','Content-Length':String(fs.statSync(target).size),'Content-Disposition':'attachment; filename="'+path.basename(target)+'"','Cache-Control':'no-store'});return fs.createReadStream(target).pipe(res)}
if(req.method==='POST'&&sub==='/security-scan')return json(res,200,{success:true,data:await scanSecurity(p)});
if(req.method==='POST'&&sub==='/test'){const b=await body(req);const result=await runTests(p,b.command||'npm test');return json(res,result.code===0?200:422,{success:result.code===0,data:result,error:result.code===0?undefined:{code:'TEST_FAILED',message:'Test command failed',details:result}})}
if(req.method==='GET'&&sub==='/git')return json(res,200,{success:true,data:await execCommand(p,'git status --short && printf "\\n---BRANCH---\\n" && git branch --show-current')});
if(req.method==='POST'&&sub==='/deploy'){requirePolicy('deployment');const b=await body(req);return json(res,200,{success:true,data:await deploy(p,{provider:b.provider||'local',repo:b.repo,branch:b.branch||'main',message:b.message})})}
if(req.method==='POST'&&sub==='/plan'){const b=await body(req);return json(res,200,{success:true,data:await plan({project:p,request:b.request})})}
if(req.method==='POST'&&sub==='/execute'){requirePolicy('model_access');const b=await body(req);if(!b.request)throw err('VALIDATION','request is required');const spec=normalizeProjectSpec({type:p.type,frontend:p.frontend,backend:p.backend,database:p.database_kind,requirements:getMemory(p.id).find(x=>x.type==='spec'&&x.key==='requirements')?.value||'',designReference:p.reference_path||''});return json(res,200,{success:true,data:await executeAgent({project:p,request:b.request,spec})})}}
if(req.method==='GET'&&u.pathname==='/api/operations'){adminUser(req);return json(res,200,{success:true,data:db.prepare('SELECT * FROM operations ORDER BY id DESC LIMIT 100').all()});}
if(req.method==='GET'&&u.pathname==='/api/credentials'){const user=adminUser(req);if(user.role!=='admin')throw err('FORBIDDEN','Admin required',403);return json(res,200,{success:true,data:listCredentials()});}
throw err('NOT_FOUND','Route not found',404);
}catch(e){console.error('[REAL ERROR]',e);return json(res,e.status||500,{success:false,error:{code:e.code||'INTERNAL_ERROR',message:e.message,details:e.details||{}}});}}
const server=http.createServer(async(req,res)=>{if(req.url.startsWith('/api/'))return route(req,res);let p=req.url==='/'?'/index.html':req.url;const file=path.normalize(path.join(frontend,p));if(!file.startsWith(frontend)||!fs.existsSync(file)||!fs.statSync(file).isFile())return json(res,404,{success:false,error:{code:'NOT_FOUND',message:'Not found'}});const ext=path.extname(file);const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(file).pipe(res);});
const port=Number(process.env.PORT||process.env.NEXORA_PORT||8787),host=process.env.NEXORA_HOST||'0.0.0.0';server.listen(port,host,()=>console.log(`Nexora AI running at http://${host}:${port}`));